server:
  port: 8080

spring:
  # 멀티 데이터소스
  datasource:
    catalog:
      url: jdbc:mysql://localhost:3306/catalog
      username: root
      password: root
    order:
      url: jdbc:mysql://localhost:3306/orders
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092