spring:
  datasource:
    url: jdbc:h2:mem:modulith;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: debug
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration